fix: Program does not exit if LED path was never found

diff --git a/keylight b/keylight
--- a/keylight
+++ b/keylight
@@ -14,7 +14,7 @@ LED_PATH_SUFFIX="::scrolllock/brightness"
 LED_PATH_COUNT=1
 LED_PATH="${LED_PATH_PREFIX}${LED_PATH_COUNT}${LED_PATH_SUFFIX}"
 
-# Also store utility variables (e.g XSET_USE_MODIFIER, PRINT_VERBOSE_INFO)
+# Also store utility variables (e.g PRINT_HELP_INFO, PRINT_VERBOSE_INFO)
 PRINT_HELP_INFO="no"
 PRINT_VERBOSE_INFO="no"
 
@@ -49,7 +49,13 @@ do
     LED_PATH="${LED_PATH_PREFIX}${LED_PATH_COUNT}${LED_PATH_SUFFIX}"
 done
 
-# DEBUG: Print the final LED path
+# If the LED path is never found, then exit.
+if [ ! -f $LED_PATH ]; then
+    echo "Cannot get keyboard device that has LED backlight."
+    exit 1
+fi
+
+# DEBUG: Print the correct LED path
 if [ $PRINT_VERBOSE_INFO == "yes" ]; then
         echo "${LED_PATH} found."
 fi
